// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgxvzzyfjpntsbhxfcjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpneHZ6enlmanBudHNiaHhmY2p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAyNzkyMDAsImV4cCI6MjA0NTg1NTIwMH0.6ubR37s249AcQa8obVp6beJzpnEPLsSGSsTRWfuMF5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);